project_id: GEN5-TO-POCKET-MONSTERS
role: target
release_id: KR-KO-HV0
platform: GBC
header_title: POKEMON_SLVAAXK
header_version: 0
size_bytes: 2097152
sha1: cb22d7e03a74dc3a563fde6be8626626b2b392e7
