schema: sakurai.dump.v4
dump_id: SWEETNDS-f94d4578
release_id: IRAO-R0
observed_file: Pokemon.White.Version.EUR.NDS-SweeTnDs.nds
provenance: SweeTnDs
size_bytes: 268435456
crc32: EDCD5161
md5: 8dfef9a099e1269af5c1fcf9d7736a11
sha1: f94d4578956487c09fee20809a591e858017769e
sha256: 93e4f473ce9a0543bccf2e689ecd07ab4fcc39dd00fb4f194343cbd5e70e17ed
internal_title: POKEMON W
game_code: IRAO
header_version: 0
unit_code: 0x02
dsi_game_revision_field: 0x4003
quality_status: bad-or-incomplete-external-preservation-classification
promotion_status: dump-specific-observation
restrictions:
  - do-not-treat-as-verified-clean-full-preservation-dump
  - twl-dsi-specific-conclusions-require-clean-dump-revalidation
  - ntr-nitrofs-analysis-may-be-retained-with-provenance
rom_binary_in_repository: false
